---
title: "Word Collocations"
---
Load necessary packages
```{r include=FALSE}
# Package names
packages <-
  c(
    "dplyr",
    "stringr",
    "purrr",
    "tidyr",
    "tidytext",
    "quanteda",
    "jsonlite",
    "ggplot2",
    "data.table",
    # "plotly",
    "forcats",
    # "ggwordcloud",
    # "ggpubr",
    "parallel",
    "dtplyr",
    "text2map",
    "quanteda.textstats"
  )

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Import media labels
# media_labels <- readRDS("../../1.data_sources/media_articles/data/media_type_labels/all_media_labels_with_doc_id.rds")

```


# X. Collocations

## X.1. Load the summarized data for selected periods

```{r}
colocs_combined <-
  bind_rows(
    readRDS("data/mainstream_2015_collocs.rds") %>% mutate(period_type = "mainstream_2015"),
    readRDS("data/alternative_2015_collocs.rds") %>% mutate(period_type = "alternative_2015"),
    readRDS("data/mainstream_2022_collocs.rds") %>% mutate(period_type = "mainstream_2022"),
    readRDS("data/alternative_2022_collocs.rds") %>% mutate(period_type = "alternative_2022")
  )

lenght_colloc <- 3L
```

## X.2. Graphing collocations

```{r}
collocs_2015_mainstream <- colocs_combined %>% 
                      filter(period_type == "mainstream_2015" & length == lenght_colloc) %>% 
                      slice_max(abs(z), n = 10) %>%
                        ggplot(aes(x = reorder(collocation, abs(z)), y = abs(z))) +
                          geom_point(color = "#0C2E49", size = 2) +
                          geom_col(fill = "#2b9bf4", width = 0.2) +
                          coord_flip() +
                          ylab(element_blank()) +
                          xlab(element_blank()) +
                          labs(title = "Collocations of Migration Content in the Czech news media: October-December 2015",
                               subtitle = "Mainstream media, top 10 using context window of 5 lemma") +
                          theme_bw() +
                          theme(
                                plot.background = element_rect(fill = "grey90"),
                                plot.title = element_text(face = "bold", size = 9),
                                plot.subtitle = element_text(face = "italic", size = 8),
                                plot.caption = element_text(size = 8),
                                axis.text = element_text(size = 8, face = "bold", color = "black"),
                                plot.margin = margin(2, 30, 2, 10, "pt"))

collocs_2015_alt <- colocs_combined %>% 
                      filter(period_type == "alternative_2015" & length == lenght_colloc) %>% 
                      slice_max(abs(z), n = 10) %>%
                        ggplot(aes(x = reorder(collocation, abs(z)), y = abs(z))) +
                          geom_point(color = "#0C2E49", size = 2) +
                          geom_col(fill = "#2b9bf4", width = 0.2) +
                        coord_flip() +
                        ylab("Wald z-statistic") +
                        xlab(element_blank()) +
                        labs(subtitle = "Alternative media, top 10 using context window of 5 lemma",
                             caption = "Data: Newton Media Archive, Search string: běženec* OR běženk* OR imigrant* OR migra* OR imigra* OR přistěhoval* OR uprchl* OR utečen* OR azylant*") +
                        theme_bw() +
                        theme(
                              plot.background = element_rect(fill = "grey90"),
                              plot.title = element_text(face = "bold", size = 10),
                              plot.subtitle = element_text(face = "italic", size = 8),
                              plot.caption = element_text(size = 4.5),
                              axis.text = element_text(size = 8, face = "bold", color = "black"),
                              axis.title.x = element_text(size = 8, color = "black"),
                              plot.margin = margin(2, 30, 2, 10, "pt"))

```


```{r}

 ggarrange(
   collocs_2015_mainstream,
   collocs_2015_alt,
   labels = c("", ""),
   ncol = 1,
   nrow = 2)
 
 ggsave("../../5.write_up/presentation_CCL_march_2022/graphics/collocs_2015.png", device = "png",
       width = 1920, height = 1080, units = "px")
 
```


```{r}
collocs_2022_mainstream <- colocs_combined %>% 
                      filter(period_type == "mainstream_2022" & length == lenght_colloc) %>% 
                      slice_max(abs(z), n = 10) %>%
                        ggplot(aes(x = reorder(collocation, abs(z)), y = abs(z))) +
                          geom_point(color = "#0C2E49", size = 2) +
                          geom_col(fill = "#2b9bf4", width = 0.2) +
                          coord_flip() +
                          ylab(element_blank()) +
                          xlab(element_blank()) +
                          labs(title = "Collocations of Migration Content in the Czech news media: February-March 2022",
                               subtitle = "Mainstream media. top 10 using context window of 5 lemma") +
                          theme_bw() +
                          theme(
                                plot.background = element_rect(fill = "grey90"),
                                plot.title = element_text(face = "bold", size = 9),
                                plot.subtitle = element_text(face = "italic", size = 8),
                                plot.caption = element_text(size = 8),
                                axis.text = element_text(size = 8, face = "bold", color = "black"),
                                plot.margin = margin(2, 30, 2, 10, "pt"))

collocs_2022_alt <- colocs_combined %>% 
                      filter(period_type == "alternative_2022" & length == lenght_colloc) %>% 
                      slice_max(abs(z), n = 10) %>%
                        ggplot(aes(x = reorder(collocation, abs(z)), y = abs(z))) +
                          geom_point(color = "#0C2E49", size = 2) +
                          geom_col(fill = "#2b9bf4", width = 0.2) +
                        coord_flip() +
                        ylab("Wald z-statistic, top 10 using context window of 5 lemma") +
                        xlab(element_blank()) +
                        labs(subtitle = "Alternative media",
                             caption = "Data: Newton Media Archive, Search string: běženec* OR běženk* OR imigrant* OR migra* OR imigra* OR přistěhoval* OR uprchl* OR utečen* OR azylant*") +
                        theme_bw() +
                        theme(
                              plot.background = element_rect(fill = "grey90"),
                              plot.title = element_text(face = "bold", size = 10),
                              plot.subtitle = element_text(face = "italic", size = 8),
                              plot.caption = element_text(size = 4.5),
                              axis.text = element_text(size = 8, face = "bold", color = "black"),
                              axis.title.x = element_text(size = 8, color = "black"),
                              plot.margin = margin(2, 30, 2, 10, "pt"))
```

# Plotting multiple graphs next to each other
```{r}
 ggarrange(
   collocs_2022_mainstream,
   collocs_2022_alt,
   labels = c("", ""),
   ncol = 1,
   nrow = 2)
 
 ggsave("../../5.write_up/presentation_CCL_march_2022/graphics/collocs_2022.png", device = "png",
       width = 1920, height = 1080, units = "px")
 
```

# New 2023 workflow

```{r}
period_name <- "2"
period_filter <- "2016|2017|2018|2019|2020|2021|2022-01"
period_exclude <- FALSE
media_type_filter <- "alternative"

cs_stop_words <- fromJSON("../../2.data_transformations/media_articles/data/stopwords_cs.json")
media_labels <- readRDS("../../1.data_sources/media_articles/data/media_type_labels/all_media_labels_with_doc_id.rds") %>%
                mutate(media_type = fct_collapse(media_type, alternative = c("antisystem", "political_tabloid"))) %>%
                filter(media_type %in% media_type_filter)

udpipe_chunks <-
  list.files(path = "../../2.data_transformations/media_articles/data/udpipe_processed/chunks/",
             pattern = "*.rds",
             full.names = TRUE) %>%
  .[grep(pattern = period_filter, ., invert = period_exclude)] 

process_df <- function(i) {
  readRDS(i) %>% 
    lazy_dt() %>%
    filter(upos %in% c("VERB", "NOUN", "ADJ", "PROPN") & doc_id %in% media_labels[["doc_id"]] & !lemma %in% cs_stop_words) %>%
    transmute(doc_id, lemma = gsub("[^ěščřžýáíéóúůďťňa-z ]", " ", tolower(str_replace_na(lemma, replacement = "")))) %>% 
    filter(nchar(lemma) > 1) %>% 
    group_by(doc_id) %>%
    summarize(text = str_squish(str_c(lemma, collapse = " "))) %>%
    ungroup() %>%
    as_tibble()
}

combined_df <- mclapply(udpipe_chunks, process_df, mc.cores = detectCores() - 1) %>% bind_rows()

saveRDS(combined_df, paste0("data/", media_type_filter, "_", period_name, ".rds"))

```


```{r}

terms_to_collocate <- c("migrant", "azylant", "imigrant", "uprchlík")
periods <- c(paste0("alternative_", 1:3), paste0("mainstream_", 1:3))
source("get_cooc_stats.R")
df <- readRDS(paste0("data/", periods, ".rds"))

cooc_stats_list <- vector("list", length = length(terms_to_collocate)) %>% setNames(terms_to_collocate)

for (term in terms_to_collocate) {

cooc_stats_list[[term]] <- df %>%
    corpus(docid_field = "doc_id", text_field = "text") %>%
    tokens(remove_punct = TRUE,
           remove_numbers = TRUE,
           padding = FALSE,
           remove_symbols = TRUE) %>%
    tokens_select(pattern = term,
                  valuetype = "fixed",
                  selection = "keep",
                  window = 3,
                  case_insensitive = TRUE,
                  padding = FALSE) %>%
    dfm(remove_padding = TRUE) %>%
    dfm_select(min_nchar = 2) %>%
    dfm_subset(ntoken(.) > 0) %>% 
    dfm_trim(min_termfreq = 2,
             termfreq_type = "count") %>% 
    calculate_cooc_stats(cooc_term = term,
                          dtm = .,
                          measure = "LogDICE")

print(paste("Term", term, "within period", periods, "finished collocation analysis."))

}

saveRDS(cooc_stats_list, paste0("data/", "stats_", periods, ".rds"))

```

```{r}
# dtm <- df %>%
#     corpus(docid_field = "doc_id", text_field = "text") %>%
#     tokens(remove_punct = TRUE,
#            remove_numbers = TRUE,
#            padding = FALSE,
#            remove_symbols = TRUE) %>%
#     tokens_select(pattern = term,
#                   valuetype = "fixed",
#                   selection = "keep",
#                   window = 3,
#                   case_insensitive = TRUE,
#                   padding = FALSE)
# 
# 
# dtm_2 <- dtm %>%
#     dfm(remove_padding = TRUE) %>%
#     dfm_select(min_nchar = 2) %>% 
#     dfm_subset(ntoken(.) > 0) %>% 
#     dfm_trim(min_termfreq = 2, termfreq_type = "count")
# 
# 
# 
# test <- dtm_2 %>%
#     calculate_cooc_stats(cooc_term = term,
#                           dtm = .,
#                           measure = "LogDICE")
```

```{r}
dtm_stats(dtm_2)

# Check columnmn names for presence of terms of interest: migrant, azylant, imigrant and uprchlík
colnames(combined_corpus)[grep(x = colnames(combined_corpus), pattern = "migrant.*|imigrant.*|azylant.*|uprchlík.*")]

```

# Create vizualizations
```{r}
terms_to_collocate <- c("migrant", "azylant", "imigrant", "uprchlík")
periods <- c(paste0("alternative_", 1:3), paste0("mainstream_", 1:3))
periods_span <- rep(c("January 2015-December 2015","January 2016-January 2022", "February 2022-February 2023"),2)
periods_media_type <- c(rep("Alternative", 3), rep("Mainstream", 3))

for (i in seq_along(periods)) {
  
cooc_stats <- readRDS(paste0("data/", "stats_", periods[[i]], ".rds"))

for (term in terms_to_collocate) {

graph <- cooc_stats[[term]] %>%
  tibble::enframe("collocate", "measure") %>%
  mutate(collocate = fct_reorder(collocate, measure)) %>%
  slice_max(order_by = measure, n = 30) %>%
  ggplot(aes(x = measure, y = collocate, label = round(measure, digits = 1))) +
    geom_col() +
    geom_label(size = 1.7, label.padding = unit(0.09, "lines")) +
    theme_classic() +
    labs(y = element_blank(), x = "LogDice", title = paste("Top 30 collocates of",
                                                           str_to_title(term),
                                                           "in Czech",
                                                           periods_media_type[[i]],
                                                           "Media,",
                                                           periods_span[[i]])) +
    theme(plot.title = element_text(face = "bold", size = 7),
        axis.title.x = element_text(size = 8),
        plot.margin = margin(7,30,3,5, "pt")) +
    scale_x_continuous(
  expand = c(0, 0),
  breaks = seq(0, 14, 1),
  labels = seq(0, 14, 1),
  limits = c(0, 14)
  )

print(paste("Term", term, "within period", periods_span[[i]], "finished exporting visualization."))

  
ggsave(graph, filename = paste0("graphs/", periods[[i]], "_", term, ".png"), device = "png", width = 1920, height = 1080, units = "px")

}
  
}
  
```

# Graph chosen for the article, modified with translations on the opposite side of the axis
```{r}

stats_mainstream_3 <- readRDS("data/stats_mainstream_3.rds")

collocation_labels <- list(
  "czech" = c(
    "Legální",
    "Počet",
    "Hranice",
    "Země",
    "Zadržet",
    "Česko",
    "Převaděč",
    "Policista",
    "Český",
    "Člověk",
    "Policie",
    "Slovensko",
    "Mluvčí",
    "Kontrola",
    "Sýrie",
    "Velký",
    "Zajistit",
    "Republika",
    "Zadržený",
    "Území",
    "Dostat",
    "Ukrajina",
    "Příliv",
    "Evropa",
    "Uprchlík",
    "Stát",
    "Přicházet",
    "Poslední",
    "Kraj",
    "Odhalit"
  ),
  "english" = c(
    "Legal",
    "Number",
    "Border",
    "Country",
    "Detain",
    "Czechia",
    "Smuggler",
    "Policeman",
    "Czech",
    "Person",
    "Police",
    "Slovakia",
    "Spokesperson",
    "Control",
    "Syria",
    "Large",
    "Secure",
    "Republic",
    "Detained",
    "Territory",
    "Get",
    "Ukraine",
    "Influx",
    "Europe",
    "Refugee",
    "State",
    "Arrive",
    "Last",
    "Region",
    "Uncover"
  )
)


stats_mainstream_3[["migrant"]] %>%
  tibble::enframe("collocate", "measure") %>%
  mutate(collocate = fct_reorder(collocate, measure)) %>%
  slice_max(order_by = measure, n = 30) %>%
  # bind_cols("original_label" = collocation_labels$czech,
  #           "translated" = collocation_labels$english) %>% 
  ggplot(aes(x = measure, y = collocate, label = round(measure, digits = 1))) +
    geom_col() +
    geom_label(size = 1.7, label.padding = unit(0.09, "lines")) +
    theme_classic() +
    labs(y = element_blank(), x = "LogDice", title = paste("Top 30 collocates of",
                                                           str_to_title("migrant"),
                                                           "in Czech",
                                                           periods_media_type[[4]],
                                                           "Media,",
                                                           periods_span[[3]])) +
    scale_x_continuous(
  expand = c(0, 0),
  breaks = seq(0, 14, 1),
  labels = seq(0, 14, 1),
  limits = c(0, 15)
  ) +
    scale_y_discrete(
    labels = rev(collocation_labels$czech)
  ) +
  geom_text(aes(label = collocation_labels$english, x = 0.1, y = collocate, fontface=1), color = "white", size = 2.5, hjust = 0) +
  # geom_vline(xintercept = 13) + 
  theme(plot.title = element_text(face = "bold", size = 7),
        axis.title.x = element_text(size = 8),
        plot.margin = margin(7,30,3,5, "pt"))


ggsave(filename = "collocations_minimalist_labels.png", device = "png", width = 1920, height = 1080, units = "px")


```

# Presentation-style graph
```{r}
# Label translations
labels <- list(
  mainstream_1 = list(
    "czech" = c(
      "Země",
      "Evropa",
      "Uprchlík",
      "Hranice",
      "Legální",
      "Počet",
      "Příliv",
      "Ekonomický",
      "Německo",
      "Člověk",
      "Stát",
      "Policie",
      "Evropský",
      "Tisíc",
      "Maďarsko"
    ),
    "english" = c(
      "Country",
      "Europe",
      "Refugee",
      "Border",
      "Legal",
      "Number",
      "Influx",
      "Economic",
      "Germany",
      "Person",
      "State",
      "Police",
      "European",
      "Thousand",
      "Hungary"
    )
  ),
  mainstream_3 = list(
    "czech" = c(
      "Legální",
      "Počet",
      "Hranice",
      "Země",
      "Zadržet",
      "Česko",
      "Převaděč",
      "Policista",
      "Český",
      "Člověk",
      "Policie",
      "Slovensko",
      "Mluvčí",
      "Kontrola",
      "Sýrie"
    ),
    "english" = c(
      "Legal",
      "Number",
      "Border",
      "Country",
      "Detain",
      "Czechia",
      "Smuggler",
      "Policeman",
      "Czech",
      "Person",
      "Police",
      "Slovakia",
      "Spokesperson",
      "Control",
      "Syria"
    )
  ),
  alternative_1 = list(
    "czech" = c(
      "Země",
      "Evropa",
      "Ekonomický",
      "Uprchlík",
      "Stát",
      "Příliv",
      "Legální",
      "Německo",
      "Evropský",
      "Hranice",
      "EU",
      "Člověk",
      "Počet",
      "Velký",
      "Kvóta"
    ),
    "english" = c(
      "Country",
      "Europe",
      "Economic",
      "Refugee",
      "State",
      "Influx",
      "Legal",
      "Germany",
      "European",
      "Border",
      "EU",
      "Person",
      "Number",
      "Large",
      "Quota"
    )
    
  ),
  alternative_3 = list(
    "czech" = c(
      "Země",
      "Legální",
      "Hranice",
      "Ukrajina",
      "Ukrajinský",
      "Evropa",
      "Počet",
      "Člověk",
      "Vláda",
      "Velký",
      "Milión",
      "Stát",
      "Uprchlík",
      "Český",
      "Příliv"
    ),
    "english" = c(
      "Country",
      "Legal",
      "Border",
      "Ukraine",
      "Ukrainian",
      "Europe",
      "Number",
      "Person",
      "Government",
      "Large",
      "Million",
      "State",
      "Refugee",
      "Czech",
      "Influx"
    )
  )
)

# common_mainstream <- intersect(labels[["alternative_1"]][["czech"]],
#                                labels[["alternative_3"]][["czech"]])

# bold_labels <- ifelse(levels(mtcars$cars) %in% common_mainstream, yes = "bold", no = "plain")

```

```{r}
media_type <- "alternative"
period_nr <- 1
period_type <- paste0(media_type,"_", period_nr)
periods <- c("January 2015-December 2015", "January 2016-January 2022", "February 2022-February 2023")
graph_color <- c("alternative" = "#fd7f6f", "mainstream" = "#b3d4ff")
collocate <- "migrant"
```

```{r}
period_data <- readRDS(paste0("data/stats_", period_type, ".rds"))[[collocate]] %>% 
  tibble::enframe("collocate", "measure") %>%
  mutate(collocate = fct_reorder(collocate, measure)) %>%
  slice_max(order_by = measure, n = 15) %>%
  bind_cols("original_label" = labels[[period_type]][["czech"]],
            "translated" = labels[[period_type]][["english"]])
  
period_data %>%  
  ggplot(aes(x = measure, y = collocate, label = round(measure, digits = 1))) +
    geom_col(fill = graph_color[[media_type]]) +
    geom_label(size = 1.7, label.padding = unit(0.09, "lines")) +
    theme_classic() +
    labs(y = element_blank(), x = "LogDice", title = paste("Top 15 collocates of",
                                                           str_to_title(collocate),
                                                           "in Czech",
                                                           str_to_title(media_type),
                                                           "Media,",
                                                           periods[[period_nr]]),
         caption = "Data: Newton Media Archive, Media types: Vaclav Cvrcek & Jan Henys (2023)") +
    scale_x_continuous(
  expand = c(0, 0),
  breaks = seq(0, 14, 1),
  labels = seq(0, 14, 1),
  limits = c(0, 14)
  ) +
    scale_y_discrete(
    labels = rev(labels[[period_type]][["czech"]])
  ) +
  geom_text(aes(label = labels[[period_type]][["english"]], x = 0.1, y = collocate, fontface=2), color = "white", size = 2.5, hjust = 0) +
  theme(axis.text = element_text(size = 7),
        plot.title = element_text(face = "bold", size = 8),
        plot.caption = element_text(size = 4.5),
        axis.title.x = element_text(size = 8),
        plot.margin = margin(7,30,3,5, "pt"))

ggsave(paste0("../../5.write_up/conference_bratislava_october_2023/graphics/collocs_", period_type, ".png"),
       width = 1920, height = 1080, units = "px")
```



