---
title: "Word Embeddings Workflow"
---
Load necessary packages
```{r include=FALSE}
# Package names
packages <-
  c(
    "dplyr",
    "stringr",
    "purrr",
    "tidyr",
    "tidytext",
    "quanteda",
    "jsonlite",
    "ggplot2",
    "data.table",
    "plotly",
    "forcats",
    "ggwordcloud",
    "ggpubr"
  )

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Import media labels
media_labels <- readRDS("../../1.data_sources/media_articles/data/media_type_labels/all_media_labels_with_doc_id.rds")

```

# 2.1 Load articles by media type and period and prepare them to be processed by 
the embedding model
```{r}
media_types <- c("mainstream", "antisystem")
periods_full <- c("2015-(10|11|12)", "2022-(02|03|04)")
periods_name <- c("2015", "2022")
udpipe_files_path <- "../../2.data_transformations/media_articles/data/udpipe_processed/chunks/"
upos_filter <- c("VERB", "NOUN", "ADJ", "PROPN")

for (o in seq_along(periods_name)) {
  period_dataset <-
    list.files(path = udpipe_files_path,
               pattern = "*.rds",
               full.names = TRUE) %>%
    .[grepl(periods_full[o], .)] %>%
    map_dfr(readRDS) %>%
    filter(upos %in% upos_filter) %>%
    mutate(word = tolower(str_replace_na(lemma, replacement = ""))) %>%
    inner_join(media_labels, by = "doc_id")
  
  for (i in media_types) {
    period_dataset %>%  
      filter(media_type %in% i) %>% 
      group_by(doc_id) %>%
      summarize(text = str_squish(str_c(word, collapse = " "))) %>%
      ungroup() %>% 
      pull(text) %>% 
      paste(collapse = "") %>% 
      writeLines(paste0("data/corpora/", i, "_", periods_name[o],".txt"))
    
    print(paste("Period", periods_name[o], "and media type", i, "finished"))
  }
}

```

# 2.2 Run and save the Word2Wang models for selected time periods and media types
```{r}

# Train the models using Wang2Vec's library written in C
corpora_list <- list.files(path = "data/corpora",
                           pattern = "*.txt",
                           full.names = FALSE)

lapply(corpora_list, function(element) {
  system(
    paste0(
      "data/wang2vec_libs/word2vec -train data/corpora/",
      element,
      " -output word_embedding/data/models/",
      gsub(element, pattern = "\\.\\w+", replacement = ""),
      " -type 1 -size 300 -window 5 -negative 10 -nce 10 -hs 0 -sample 1e-4 -threads 12 -binary 1 -iter 20 -cap 0"
    )
  )
})

```

```{r}
library(word2vec)

node_words <- c("uprchlík", "migrant") %>% tolower()
# node_words <- c("vídeň", "rakousko") %>% tolower()
models <- c("alternative_2015", "alternative_2022", "mainstream_2015", "mainstream_2022")
list_of_predictions <- vector("list", length = length(models)) %>% setNames(models)
number_of_predictions <- 30L

for (i in models) {
  set.seed(3859)
  model <- read.word2vec(file = paste0("data/models/", i), normalize = TRUE)
  list_of_predictions[[i]] <- predict(model, node_words, type = "nearest", top_n = number_of_predictions) %>% bind_rows()
  }

predictions_df <- bind_rows(list_of_predictions, .id = "model")

```

Embeddings Visualizations

```{r}
# For 2015
set.seed(3859)
predictions_df %>% 
  filter(model %in% c("alternative_2015", "mainstream_2015")) %>% 
  group_by(model, term1) %>% 
  mutate(similarity_scaled = (similarity - min(similarity)) / (max(similarity) - min(similarity))) %>% 
  ungroup() %>% 
ggplot(aes(label = term2, size = similarity_scaled, color = similarity_scaled)) +
  geom_text_wordcloud(
    area_corr = TRUE,
    max_steps = 1,
    grid_size = 1,
    eccentricity = .9
  ) +
  scale_size_area(max_size = 10.5) +
  scale_color_gradient2(low = "#fcffdd", mid = "#18bdb0", high = "#2a1d62") +
  facet_grid(rows = vars(term1), cols = vars(model), switch = "y") +
labs(title = "Similarly used Words in the Czech News Media Migration Coverage (October-December 2015)",
       subtitle = "Word Embeddings. Split by media type and lemmatized term, top 30.",
       caption = "Data: Newton Media Archive, UDPIPE Czech: Milan Straka & Jana Straková (2020), Wang2Vec: Ling, Wang and Dyer, Chris and Black, Alan and Trancoso, Isabel (2015)") +
  theme_void() +
  theme(plot.background = element_rect(fill = "grey90"),
        plot.title = element_text(face = "bold", size = 10, margin = margin(0, 0, 3, 0)),
        plot.subtitle = element_text(face = "italic", size = 8, margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 5),
        panel.border = element_rect(colour = "black",
                                    fill = NA,
                                    size = 0.5),
        plot.margin = margin(7, 30, 5, 5, "pt"))

ggsave("../../5.write_up/presentation_CCL_march_2022/graphics/embedding_2015.png", device = "png",
       width = 1920, height = 1080, units = "px")


# For 2022
set.seed(3859)
predictions_df %>% 
  filter(model %in% c("alternative_2022", "mainstream_2022")) %>% 
  group_by(model, term1) %>% 
  mutate(similarity_scaled = (similarity - min(similarity)) / (max(similarity) - min(similarity))) %>% 
  ungroup() %>% 
ggplot(aes(label = term2, size = similarity_scaled, color = similarity_scaled)) +
  geom_text_wordcloud(
    area_corr = TRUE,
    max_steps = 1,
    grid_size = 1,
    eccentricity = .9
  ) +
  scale_size_area(max_size = 9) +
  scale_color_gradient2(low = "#e7d39a", mid = "#f27b68", high = "#4b1d91") +
  facet_grid(rows = vars(term1), cols = vars(model), switch = "y") +
labs(title = "Similarly used Words in the Czech News Media Migration Coverage (February-April 2022)",
       subtitle = "Word Embeddings. Split by media type and lemmatized term, top 30.",
       caption = "Data: Newton Media Archive, UDPIPE Czech: Milan Straka & Jana Straková (2020), Wang2Vec: Ling, Wang and Dyer, Chris and Black, Alan and Trancoso, Isabel (2015)") +
  theme_void() +
  theme(plot.background = element_rect(fill = "grey90"),
        plot.title = element_text(face = "bold", size = 10, margin = margin(0, 0, 3, 0)),
        plot.subtitle = element_text(face = "italic", size = 8, margin = margin(0, 0, 10, 0)),
        plot.caption = element_text(size = 5),
        panel.border = element_rect(colour = "black",
                                    fill = NA,
                                    size = 0.5),
        plot.margin = margin(7, 30, 5, 5, "pt"))

ggsave("../../5.write_up/presentation_CCL_march_2022/graphics/embedding_2022.png", device = "png",
       width = 1920, height = 1080, units = "px")

```

